#include "melting_gen.h"

#include "cJSON.h"

#include <stdio.h>
#include <string.h>

static void ScriptToText(const GenItem *item, char *out, size_t outSize)
{
    out[0] = '\0';
    size_t used = 0;
    for (int i = 0; i < item->opCount; i++)
    {
        const GenScriptOp *op = &item->ops[i];
        int n = snprintf(out + used, outSize - used, "%s%s:%s,%g,%g,%s",
                         i > 0 ? "|" : "", op->trigger, op->op, op->a, op->b, op->trait);
        if (n < 0 || (size_t)n >= outSize - used) break;
        used += (size_t)n;
    }
}

static void TraitsToText(const GenItem *item, char *out, size_t outSize)
{
    out[0] = '\0';
    size_t used = 0;
    for (int i = 0; i < item->traitCount; i++)
    {
        int n = snprintf(out + used, outSize - used, "%s%s", i > 0 ? "," : "", item->traits[i]);
        if (n < 0 || (size_t)n >= outSize - used) break;
        used += (size_t)n;
    }
}

static int WriteManifest(const GenRun *run, const char *outDir)
{
    char path[512];
    snprintf(path, sizeof(path), "%s/current_run.txt", outDir);
    FILE *f = fopen(path, "w");
    if (!f) return -1;
    fprintf(f, "# Generated by melting-gen\n");
    fprintf(f, "source=%s\n", run->source);
    fprintf(f, "seed=%u\n", run->seed);
    /* Percorso fisso, non derivato da outDir: stesso valore letterale del
       fallback in llm/run_content.mjs (runToManifest / writePlayableAtlas),
       che scrive sempre "generated/current_atlas.bmp" perche' Node non ha
       un equivalente di --out. Interpolare outDir qui romperebbe sia la
       parita' di formato col generatore Node sia il test di determinismo
       di scripts/test-gen.sh, che confronta due run con lo stesso seed
       scritte in --out diversi e si aspetta manifest identici byte-a-byte. */
    fprintf(f, "atlas.path=generated/current_atlas.bmp\n");
    for (int fl = 0; fl < GEN_FLOORS; fl++)
    {
        const GenFloor *floor = &run->floors[fl];
        int n = fl + 1;
        fprintf(f, "floor%d.theme=%s\n", n, floor->theme);
        fprintf(f, "floor%d.style=%s\n", n, floor->style);
        fprintf(f, "floor%d.boss=%s\n", n, floor->boss);
        fprintf(f, "floor%d.bg=%s\n", n, floor->bg);
        fprintf(f, "floor%d.floor=%s\n", n, floor->floorColor);
        fprintf(f, "floor%d.wall=%s\n", n, floor->wall);
        fprintf(f, "floor%d.accent=%s\n", n, floor->accent);
        fprintf(f, "floor%d.accent2=%s\n", n, floor->accent2);
        fprintf(f, "floor%d.enemy=%s\n", n, floor->enemy);
        fprintf(f, "floor%d.bossColor=%s\n", n, floor->bossColor);
        for (int i = 0; i < GEN_ITEMS; i++)
        {
            const GenItem *item = &floor->items[i];
            char text[256];
            fprintf(f, "floor%d.item%d.name=%s\n", n, i + 1, item->name);
            fprintf(f, "floor%d.item%d.slot=%s\n", n, i + 1, item->slot);
            TraitsToText(item, text, sizeof(text));
            fprintf(f, "floor%d.item%d.traits=%s\n", n, i + 1, text);
            fprintf(f, "floor%d.item%d.color=%s\n", n, i + 1, item->color);
            ScriptToText(item, text, sizeof(text));
            fprintf(f, "floor%d.item%d.script=%s\n", n, i + 1, text);
        }
    }
    fclose(f);
    return 0;
}

/* Ordine di inserimento = ordine chiavi di run.gbnf: la coppia writer/grammatica
   viene verificata da test-gen (Task 5). */
static cJSON *RunToJson(const GenRun *run)
{
    cJSON *root = cJSON_CreateObject();
    cJSON *floors = cJSON_AddArrayToObject(root, "floors");
    for (int fl = 0; fl < GEN_FLOORS; fl++)
    {
        const GenFloor *floor = &run->floors[fl];
        cJSON *jf = cJSON_CreateObject();
        cJSON_AddStringToObject(jf, "theme", floor->theme);
        cJSON_AddStringToObject(jf, "style", floor->style);
        cJSON_AddStringToObject(jf, "boss", floor->boss);
        cJSON_AddStringToObject(jf, "bg", floor->bg);
        cJSON_AddStringToObject(jf, "floor", floor->floorColor);
        cJSON_AddStringToObject(jf, "wall", floor->wall);
        cJSON_AddStringToObject(jf, "accent", floor->accent);
        cJSON_AddStringToObject(jf, "accent2", floor->accent2);
        cJSON_AddStringToObject(jf, "enemy", floor->enemy);
        cJSON_AddStringToObject(jf, "bossColor", floor->bossColor);
        cJSON *items = cJSON_AddArrayToObject(jf, "items");
        for (int i = 0; i < GEN_ITEMS; i++)
        {
            const GenItem *item = &floor->items[i];
            cJSON *ji = cJSON_CreateObject();
            cJSON_AddStringToObject(ji, "name", item->name);
            cJSON_AddStringToObject(ji, "slot", item->slot);
            cJSON *traits = cJSON_AddArrayToObject(ji, "traits");
            for (int t = 0; t < item->traitCount; t++)
            {
                cJSON_AddItemToArray(traits, cJSON_CreateString(item->traits[t]));
            }
            cJSON_AddStringToObject(ji, "color", item->color);
            cJSON *script = cJSON_AddArrayToObject(ji, "script");
            for (int s = 0; s < item->opCount; s++)
            {
                const GenScriptOp *op = &item->ops[s];
                cJSON *jo = cJSON_CreateObject();
                cJSON_AddStringToObject(jo, "trigger", op->trigger);
                cJSON_AddStringToObject(jo, "op", op->op);
                cJSON_AddNumberToObject(jo, "a", op->a);
                cJSON_AddNumberToObject(jo, "b", op->b);
                cJSON_AddStringToObject(jo, "trait", op->trait);
                cJSON_AddItemToArray(script, jo);
            }
            cJSON_AddItemToArray(items, ji);
        }
        cJSON_AddItemToArray(floors, jf);
    }
    return root;
}

int GenWriteLlmJson(const GenRun *run, const char *path)
{
    cJSON *root = RunToJson(run);
    char *text = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!text) return -1;
    FILE *f = fopen(path, "w");
    if (!f) { cJSON_free(text); return -1; }
    fputs(text, f);
    fclose(f);
    cJSON_free(text);
    return 0;
}

int GenWriteRunFiles(const GenRun *run, const char *outDir)
{
    if (GenEnsureDir(outDir) != 0) return -1;
    if (WriteManifest(run, outDir) != 0) return -1;

    char atlasPath[300];
    snprintf(atlasPath, sizeof(atlasPath), "%s/current_atlas.bmp", outDir);

    cJSON *root = RunToJson(run);
    cJSON_AddStringToObject(root, "source", run->source);
    cJSON_AddNumberToObject(root, "seed", run->seed);
    cJSON *atlas = cJSON_AddObjectToObject(root, "atlas");
    cJSON_AddStringToObject(atlas, "path", atlasPath);
    cJSON_AddNumberToObject(atlas, "cellSize", 128);
    cJSON_AddNumberToObject(atlas, "columns", 8);
    char *text = cJSON_Print(root);
    cJSON_Delete(root);
    if (!text) return -1;
    char path[512];
    snprintf(path, sizeof(path), "%s/current_run.json", outDir);
    FILE *f = fopen(path, "w");
    if (!f) { cJSON_free(text); return -1; }
    fprintf(f, "%s\n", text);
    fclose(f);
    cJSON_free(text);

    snprintf(path, sizeof(path), "%s/current_atlas.json", outDir);
    f = fopen(path, "w");
    if (!f) return -1;
    fprintf(f,
        "{\n"
        "  \"path\": \"%s\",\n"
        "  \"width\": 1024,\n  \"height\": 1024,\n"
        "  \"cellSize\": 128,\n  \"columns\": 8,\n  \"rows\": 8,\n"
        "  \"sprites\": {\n"
        "    \"player\": [0, 0], \"enemy_chaser\": [1, 0], \"enemy_shooter\": [2, 0],\n"
        "    \"enemy_tank\": [3, 0], \"boss\": [4, 0], \"item\": [5, 0], \"heart\": [6, 0],\n"
        "    \"coin\": [7, 0], \"bomb\": [0, 1], \"key\": [1, 1], \"exit\": [2, 1], \"shot\": [3, 1]\n"
        "  }\n"
        "}\n",
        atlasPath);
    fclose(f);
    return 0;
}
